name: task_manager
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.8.4
  flutter_riverpod: ^2.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0
  flutter_animate: ^4.2.0
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.5.3
  pinput: ^5.0.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true